### PR TITLE
Added Deployr to ingestor

### PR DESCRIPTION
**Pull request by cpritcha**
- Added Packrat lock file display (using pygments)
- Integrated deployr loading into ingestor
  - Analyses and projects are added to deployr when an archive is processed
- Moved Deployr configuration to local.py
- Removed skeleton.zip
- Updated URLs with task status
- Added packrat upload directory

### CODE REVIEW

**Comment by cpritcha** [comment]
One integration test depends on the deployr server. I could create a more full interface to deployr and mock the return values.

**Comment by alee** [comment]
Is there a reason you removed AnalysisParameter and ParameterValues? These are needed to run the analyses against the DeployR server..

**Comment by cpritcha** [comment]
The `AnalysisOutput` model has a field named `parameter_values_json` which we can use to store the parameter values. The `DataAnalysisScript` has a field named `parameters_json` which we could use to store the parameters. I thought that we should either get rid of the `AnalysisParameter` and `ParameterValues` tables or the JSON fields because they seem to store the same data. I chose to get rid of the tables because some the raw json parameter values do not always have the same fields (in the *luxedemo* example, one of the controls has a `valueList` field and the other has a `valueRange` field).

**Comment by alee** [comment]
1. instead of using Project.name, use Project.slug for the short name (in extract_archive)
2. 
```
Task miracle.core.tasks.extract_archive[2a151f33-7803-482a-a640-f93798b8299a] raised unexpected: EncodeError(PicklingError("Can't pickle <class 'miracle.core.ingest.ProjectFilePath'>: attribute lookup miracle.core.ingest.ProjectFilePath failed",),)
...
EncodeError: Can't pickle <class 'miracle.core.ingest.ProjectFilePath'>: attribute lookup miracle.core.ingest.ProjectFilePath failed
```

**Pull request merged**
