### PR TITLE
Add basic metadata import functionality and vagrant

### PR DESCRIPTION
**Pull request by cpritcha**
This merge has some basic metadata extraction functions for reading file metadata.

### CODE REVIEW

**Comment by cpritcha** [comment]
coveralls does not seem to find my tests. What changes do I need to make to the fabfile?

**Comment by alee** [comment]
Thanks Calvin! 

Some suggestions:

1. Move dataloader.py to `core/metadata.py` and remove the `dataloader` app
2. Move tests to core/tests/test_metadata.py` - coveralls should find them then
3. I assume the files in the `data` directory are just for the tests? If so, let's put them in `tests/data` - you should be able to refer to them via relative paths (or you can construct an absolute path using settings.BASE_DIR if needed)
4. Replace print usage with the logging module
5. Finally, consider squashing the commits into a cohesive whole afterwards: http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by alee** [comment]
Hi Calvin, sorry for the extra work but could you please rebase this pull request against the latest master? 

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by cpritcha** [comment]
Sure. I'll do that and then merge in the changes.

**Pull request merged**
