### PR TITLE
Get docker-compose build working

### PR DESCRIPTION
**Pull request by cpritcha**
- fixed container linking issue
- got working with nginx
  - created self signed ssl certificate so CSRF works
  - matched uids with the host nginx
  - created volume directory in Dockerfile so that volume has correct user
  - added proxy to radiant with nginx
  - changed X-Frame-Options from DENY to SAMEORIGIN
- verified that celery works in the container
- split requirements into different files for production and local development
- inject user into django on startup with an environment variable
- added `docker-compose.yml` to `.gitignore`

### CODE REVIEW

**Comment by cpritcha** [comment]
Showstoppers
===========

- Have to figure out why metadata is rolling back adding the metadata to the database (it seems to be that the DeployR connection is not quite right but I'll have to investigate further)
- Haven't tested the Radiant and Django connection
- Haven't checked if Celery is working properly in the container

**Comment by cpritcha** [comment]
DeployR
=======

I can use get requests in the django container and the deployr server responds the same as on my host machine

### Host

```python
>>> requests.get("http://localhost:7400/deployr/administration/login")  
<Response [200]>
```

I also added deployr to my */etc/hosts* file

```python
>>> requests.get("http://deployr:7400/deployr/administration/login")  
<Response [200]>
```

### Django Container

```python
In [5]: requests.get("http://deployr:7400/deployr/administration/login")                                                                               
INFO 2016-01-15 22:30:09,754 [requests.packages.urllib3.connectionpool|_new_conn:207] Starting new HTTP connection (1): deployr
Out[5]: <Response [200]>
```

However, when I do a login request I get a 404 error (this code is the same as the login code used `deployr.py` file)

### Host and Django Container

```python
>>> s = requests.Session()
>>> r = s.post("http://deployr:7400/r/user/login", data={'username': 'miracle', 'password': 'CHANGEME', 'format': 'json'}) 
>>> r
<Response [404]>
```

But if I use curl to authenticate it works on the host and in the Django container

```
curl -c cookies.txt --verbose --data "format=json&username=miracle&password=CHANGEME" \
                                   http://deployr:7400/deployr/r/user/login
```

Any suggestions @alee @warmdev ?

**Comment by warmdev** [comment]
Was the 404 issue resolved? I think it was due to a hostname issue. When not specified using the `setWebContext` command, it was defaulted to `localhost`, and even though you can open the login page using `http://deployr:7400/...`, it will redirect to `http://localhost:7400/...`, thus generating a 404 error.

**Comment by cpritcha** [comment]
I found out what the issue was. I was just using the wrong url. I needed `http://deployr:7400/deployr/` not the `http://deployr:7400/` that I was trying to use.

**Comment by cpritcha** [comment]
The important pieces are done. Ready to merge.

**Comment by warmdev** [comment]
Great job @cpritcha ! Could you add installation of R dependencies for `luxedemo` and `rhea` to the Dockerfiles (`radiant` and `deployr`)? This will make deployment and testing easier.

**Comment by cpritcha** [comment]
Sure. I'll add the R library dependencies.

**Comment by cpritcha** [comment]
CentOS got rid of the `which` shell command from their install in the last few days which broke the DeployR install. I'm rebuilding and will put up the version with R dependencies shortly.

**Comment by cpritcha** [comment]
The SysV service doesn't seem to work either... `etc/rc.d/init.d/functions` does not exist. I'll try to pin to an old CentOS version.

**Comment by warmdev** [comment]
There might be an warning or error with `etc/rc.d/init.d/functions` but it does not seem to affect DeployR from working in my own test.

**Comment by cpritcha** [comment]
Oh. OK. There must be something else wrong then because it still isn't running properly. That was the error I got so I hoped that was it.

**Comment by warmdev** [comment]
Could you send your files to me and I'll help with testing.

**Comment by cpritcha** [comment]
Sure. I'll post in a few minutes.

**Comment by cpritcha** [comment]
I just posted my changes to my fork. Be sure to `docker pull centos:7` to get the latest CentOS changes.

**Comment by cpritcha** [comment]
I ran the [diagnostics script](https://gist.github.com/cpritcha/cb2e206fad7613d76320) and it says that the "login failed"

**Pull request merged**
