### PR TITLE
Added command line project loader

### PR DESCRIPTION
**Pull request by cpritcha**
- added database support
- ensured `load_project` works in docker

### CODE REVIEW

**Comment by cpritcha** [comment]
Works on my machine in vagrant and docker. Any suggestions @alee?

**Comment by cpritcha** [comment]
I've tried rebuilding the databases `fab rebuild_database` and recreating the docker containers but migrations still work.

**Comment by alee** [comment]
Sure, I'll take a look in a little bit. Am currently trying to finish debugging some issues with remote R script execution.

**Comment by cpritcha** [comment]
Seems to have to do with oauth [204](https://github.com/evonove/django-oauth-toolkit/issues/204).

**Comment by cpritcha** [comment]
The latest change gets it to run up to `fab coverage`. I got it to go a bit further by making sure django applies oauth migrations first. Still fails with the same error `ProgrammingError: relation "auth_user" does not exist`

**Comment by cpritcha** [comment]
Got it to not work on my machine. 

In order to get this working I need to be able to apply the auth migrations in the test database before the other migrations.

**Comment by cpritcha** [comment]
I can get a fresh clone to work on my local machine by copying all my old migrations (including the binary `.pyc` files) to the clone. Without the `.pyc` files it does not work.

**Comment by cpritcha** [comment]
I'll add changes one by one and see where it breaks. That seems easier than trying to change the order the migrations are done in the test runner.

**Comment by cpritcha** [comment]
I merged a copy of the command line loader after checking in the files one by one. Everything seems to work now (but I'm not sure why it was not working before).

**Pull request closed without merging**
